---
- name: Get Containerd
  unarchive:
    src: "https://storage.googleapis.com/cri-containerd-release/cri-containerd-{{ containerd_version }}.linux-amd64.tar.gz"
    dest: "/"
    remote_src: yes
  when: cri_runtime == 'containerd'

- name: Create a directory for cni binary
  file: path={{ cni_bin_dir }} state=directory
  when: cri_runtime == 'containerd'

- name: Create a directory for cni config files
  file: path={{ cni_conf_dir }} state=directory
  when: cri_runtime == 'containerd'

- name: Create a directory for containerd config
  file: path=/etc/containerd state=directory
  when: cri_runtime == 'containerd'

- name: Start Containerd
# systemd: name=containerd daemon_reload=yes state=started enabled=yes
  systemd:
    name: containerd
    daemon_reload: yes
    state: started
    enabled: yes
  when: cri_runtime == 'containerd'
