---
- debug:
    msg:
    - "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }} // {{ cri_runtime }}"

- name: Get Containerd
  unarchive:
    src: "https://storage.googleapis.com/cri-containerd-release/cri-containerd-{{ containerd_version }}.linux-amd64.tar.gz"
    dest: "/"
    remote_src: yes
  when: cri_runtime == 'containerd'

- name: Make Containerd dirs
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ cni_bin_dir }}'
    - '{{ cni_conf_dir }}'
    - '/etc/containerd/'
  when: cri_runtime == 'containerd'

- name: Start Containerd
# systemd: name=containerd daemon_reload=yes state=started enabled=yes
  systemd:
    name: containerd
    daemon_reload: yes
    state: started
    enabled: yes
  when: cri_runtime == 'containerd'
