---
- name: Add etcd user
  user:
    name: etcd
    group: root
    shell: /bin/false
    state: present
  when: inventory_hostname == play_hosts[0]

- name: Make etcd dirs
  file:
    path: '{{ item }}'
    state: directory
    owner: etcd
    mode: '0755'
  with_items:
    - /opt/etcd
    - /opt/etcd/bin
    - /opt/etcd/data
  when: inventory_hostname == play_hosts[0]

- name: Download/Unpack EtcD
  unarchive:
    src: 'https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz'
    dest: /opt/etcd/bin
    remote_src: yes
    extra_opts:
      - '--strip'
      - '1'
      - '--exclude'
      - 'etcd-v{{ etcd_version }}-linux-amd64/[A-Z]*'
  when: inventory_hostname == play_hosts[0]

- name: Create EtcD service file
  copy:
    mode: '0644'
    dest: /lib/systemd/system/etcd.service
    content: |
      [Unit]
      Description=etcd key-value store
      After=network.target

      [Service]
      User=etcd
      Type=notify
      PermissionsStartOnly=true
      Environment=ETCD_NAME=%H
      EnvironmentFile=-/etc/default/%p
      ExecStart=/opt/etcd/bin/etcd \
          --advertise-client-urls http://localhost:2379,http://{{ hostvars[play_hosts[0]].ansible_eth1.ipv4.address }}:2379 \
          --listen-client-urls http://0.0.0.0:2379 \
          --data-dir /opt/etcd/data \
          --auto-compaction-mode=revision --auto-compaction-retention=1000
      Restart=on-abnormal
      RestartSec=10s
      LimitNOFILE=40000

      [Install]
      WantedBy=multi-user.target
  when: inventory_hostname == play_hosts[0]

- name: Enable EtcD
  systemd:
    name: etcd
    daemon_reload: yes
    state: started
    enabled: yes
  when: inventory_hostname == play_hosts[0]
