---
- name: Add etcd user
  user:
    name: etcd
    group: root
    shell: /bin/false
    state: present

- name: Make etcd dirs (1)
  file:
    path: "{{ item }}"
    state: directory
    owner: etcd
    mode: "0755"
  with_items:
    - /opt/etcd
    - /opt/etcd/bin

- name: Make etcd dirs (2)
  file:
    path: "{{ item }}"
    state: directory
    owner: etcd
    mode: "0700"
  with_items:
    - /opt/etcd/data

- name: Download/Unpack EtcD
  unarchive:
    src: "https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    dest: /opt/etcd/bin
    remote_src: yes
    extra_opts:
      - "--strip"
      - "1"
      - "--exclude"
      - "etcd-v{{ etcd_version }}-linux-amd64/[A-Z]*"
    creates: /opt/etcd/bin/etcd

- name: Create EtcD service file
  copy:
    mode: "0644"
    dest: /lib/systemd/system/etcd.service
    content: |
      [Unit]
      Description=etcd key-value store
      After=network.target

      [Service]
      User=etcd
      Type=notify
      PermissionsStartOnly=true
      Environment=ETCD_NAME=%H
      EnvironmentFile=-/etc/default/%p
      ExecStart=/opt/etcd/bin/etcd \
          --advertise-client-urls http://localhost:2379,http://{{ k8s_master_ip }}:2379 \
          --listen-client-urls http://0.0.0.0:2379 \
          --data-dir /opt/etcd/data \
          --auto-compaction-mode=revision --auto-compaction-retention=1000
      Restart=on-abnormal
      RestartSec=10s
      LimitNOFILE=40000

      [Install]
      WantedBy=multi-user.target

- name: Enable EtcD
  systemd:
    name: etcd
    daemon_reload: yes
    state: started
    enabled: yes
