---
# NOTE: this assumes main network interface is 'eth1'
- name: Update /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {% for item in ansible_play_hosts %}
      {{ hostvars[item].ansible_eth1.ipv4.address }}	{{ item }}
      {% endfor %}

- name: Update /etc/sysconfig/network (RedHat)
  blockinfile:
    path: /etc/sysconfig/network
    block: |
      GATEWAYDEV=eth1
  when: ansible_os_family == 'RedHat'

- name: Restart network (RedHat)
  systemd:
    name: network
    state: restarted
  when: ansible_os_family == 'RedHat'
