---
- name: Make kubelet dir
  file:
    path: "{{ kubelet_dir }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  when: kubelet_dir is defined

- name: Update kubelet root-dir (CentOS)
  lineinfile:
    path: '{{ kubelet_vars }}'
    state: present
    regexp: '^KUBELET_EXTRA_ARGS='
    line: 'KUBELET_EXTRA_ARGS=--root-dir={{ kubelet_dir }}'
  when: kubelet_dir is defined

# ---------------------------------------------

- name: Update kubelet for containerd
  lineinfile:
    path: '{{ kubelet_vars }}'
    state: present
    regexp: '^KUBELET_EXTRA_ARGS='
    line: 'KUBELET_EXTRA_ARGS=--runtime-cgroups=/system.slice/containerd.service --runtime-request-timeout=15m --container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock"'
  when: cri_runtime == 'containerd'

# ---------------------------------------------

- name: Update kubelet for CRI-O
  lineinfile:
    path: '{{ kubelet_vars }}'
    state: present
    regexp: '^KUBELET_EXTRA_ARGS='
    line: 'KUBELET_EXTRA_ARGS=--feature-gates="AllAlpha=false,RunAsGroup=true" --cgroup-driver=systemd --runtime-request-timeout=5m --container-runtime=remote --container-runtime-endpoint=unix:///var/run/crio/crio.sock'
  when: cri_runtime == 'cri-o'

