---
- name: CA extras directory check
  file:
    path: "{{ ca_certs_dir }}"
    state: directory

- name: Create PWX CA file
  copy:
    owner: root
    group: root
    mode: "0600"
    dest: "{{ ca_certs_dir }}/PWX_ca.crt"
    content: "{{ pwx_ca }}"

# ---------------------------------------------

- name: Add PWX_ca (Ubuntu)
  lineinfile:
    path: /etc/ca-certificates.conf
    state: present
    line: "extra/PWX_ca.crt"
  when: ansible_os_family == 'Debian'

- name: Refresh certs (Ubuntu)
  command: update-ca-certificates
  when: ansible_os_family == 'Debian'

# ---------------------------------------------

- name: Refresh certs (CentOS)
  command: update-ca-trust force-enable
  when: ansible_os_family == 'RedHat'

- name: Extract certs (CentOS)
  command: update-ca-trust extract
  when: ansible_os_family == 'RedHat'
