---
- name: Turn off swap
  shell: |
    if [ `wc -l < /proc/swaps` -gt 1 ]; then
      grep -v '^#' /etc/fstab | awk '/swap/{print $1}' | xargs -rn1 swapoff
      sed -i -e 's/.*swap.*/# \0  # ANSIBLE/' /etc/fstab
      if [ -f /swapfile ]; then
        rm -f /swapfile
      fi
    fi
