---
- hosts: all
  remote_user: vagrant
  become: true
  become_method: sudo
  become_user: root

  tasks:
    - name: Install packages
      package:
        name:
          - zsh
          - git
          - rsync
          - psmisc
          - net-tools
          - jq
        state: present

    - name: Stop services
      systemd:
        name: '{{ item }}'
        state: stopped
        enabled: yes
      with_items:
        - snapd
        - atd
        - iscsi
        - iscsid
        - lxcfs
      ignore_errors: true

    - name: Create zox user
      user:
        name: zox
## create passwd w/ mkpasswd --method=sha-512
        password: '$6$sw16qsF1uSkyp$aIfc1qYflfBWMZDPFhtNXc/wcWUC0UmuNZdDmVjS56iNj4YYFAu19hYbkYXMu/LokB6rEjH/8F9IUm/ZvTG251'
        uid: 501
        group: 100
        groups:
          - bin
          - systemd-journal
        state: present
        shell: /bin/zsh

    - name: Unpack /home/zox
      unarchive:
        src: /srv/salt/zox/zox_home.tar.gz
        dest: /home/zox
        extra_opts:
          - '-zvPp'
        creates: /home/zox/.vim/colors/zox.vim

    - name: Create sudo for zox
      copy:
        dest: /etc/sudoers.d/003-zox
        mode: 0644
        content: |
          zox   ALL=NOPASSWD: ALL
