---
- hosts: all
  remote_user: vagrant
  become: true
  become_method: sudo
  become_user: root
  strategy: free

  tasks:
    - name: PreInstall packages  (CentOS)
      package:
        name:
          - epel-release
          - container-selinux
          - selinux-policy-base
        state: present
        update_cache: yes
      when: ansible_os_family == 'RedHat'

    - name: Install packages
      package:
        name:
          - zsh
          - vim
          - curl
          - git
          - rsync
          - psmisc
          - net-tools
          - jq
        state: present

    - name: Stop services
      systemd:
        name: '{{ item }}'
        state: stopped
        enabled: yes
      with_items:
        - snapd
        - atd
        - iscsi
        - iscsid
        - lxcfs
      ignore_errors: true

    - name: Create zox user
      user:
        name: zox
## create passwd w/ mkpasswd --method=sha-512
        password: '$6$sw16qsF1uSkyp$aIfc1qYflfBWMZDPFhtNXc/wcWUC0UmuNZdDmVjS56iNj4YYFAu19hYbkYXMu/LokB6rEjH/8F9IUm/ZvTG251'
        uid: 501
        group: users
        groups:
          - root
          - bin
          - systemd-journal
        state: present
        shell: /bin/zsh

    - name: Unpack /home/zox
      unarchive:
        src: /srv/salt/zox/zox_home.tar.gz
        dest: /
        extra_opts:
          - '-zPp'
        creates: /home/zox/.vim/colors/zox.vim

    - name: Create sudo for zox
      copy:
        dest: /etc/sudoers.d/003-zox
        mode: 0644
        content: |
          zox   ALL=NOPASSWD: ALL

    - name: Copy kubeconfig (if any)
      shell: |
        if [ -f /root/.kube/config ] && [ ! -f /home/zox/.kube/config ]; then
          install -Zb -m 700 -o zox -g users -d /home/zox/.kube
          install -Zb -m 600 -o zox -g users -D /root/.kube/config /home/zox/.kube/config
        fi
      args:
        creates: /home/zox/.kube/config
